export class Catalogo {
  idempresa: number;
  CUENTA: string ;
  CTADEP: string ;
  NOMBRE: string ;
  NIVEL: number ;
  TIPO: number ;
  TRANSA: boolean ;
  CTABANCO: boolean;
  CTALIBROS: string ;
  USUARIO: string ;
  ACCESO: Date ;
  SALINI: number;
  CAR01: number ;
  ABO01: number;
  SAL01: number;
  CAR02: number;
  ABO02: number;
  SAL02: number;
  CAR03: number;
  ABO03: number;
  SAL03: number;
  CAR04: number;
  ABO04: number;
  SAL04: number;
  CAR05: number;
  ABO05: number;
  SAL05: number;
  CAR06: number;
  ABO06: number;
  SAL06: number;
  CAR07: number;
  ABO07: number;
  SAL07: number;
  CAR08: number;
  ABO08: number;
  SAL08: number;
  CAR09: number;
  ABO09: number;
  SAL09: number;
  CAR10: number;
  ABO10: number;
  SAL10: number;
  CAR11: number;
  ABO11: number;
  SAL11: number;
  CAR12: number;
  ABO12: number;
  SAL12: number;
  ESTADOS: boolean;
  DIASCRED: number;
  REGISTRO: string;
  KEY: string
  PARENT: string;
}
